import esbuild from "esbuild";
import process from "process";
import fs from "fs";
import path from "path";

const prod = process.argv[2] === "production";

// Node.js built-in modules that sql.js tries to import but doesn't need in browser/Electron
const nodeBuiltins = ['fs', 'path', 'crypto'];

// Generate inline WASM as base64 (embedded in bundle for Obsidian Sync compatibility)
const inlineWasmPlugin = {
    name: 'inline-wasm',
    setup(build) {
        build.onStart(() => {
            const wasmSource = path.join('node_modules', 'sql.js', 'dist', 'sql-wasm.wasm');

            if (fs.existsSync(wasmSource)) {
                const wasmBuffer = fs.readFileSync(wasmSource);
                const base64 = wasmBuffer.toString('base64');
                const outputPath = path.join('src', 'wasm-data.ts');
                const content = `// Auto-generated by esbuild - DO NOT EDIT
// This file contains sql-wasm.wasm encoded as base64
// Size: ${wasmBuffer.length} bytes (${(wasmBuffer.length / 1024 / 1024).toFixed(2)} MB)
export const SQL_WASM_BASE64 = "${base64}";
`;
                fs.writeFileSync(outputPath, content);
                console.log(`Generated inline WASM base64 (${(wasmBuffer.length / 1024 / 1024).toFixed(2)} MB)`);
            } else {
                console.warn('Warning: sql-wasm.wasm not found in node_modules');
            }
        });
    }
};

const context = await esbuild.context({
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        // Node.js builtins - will be required at runtime via window.require if needed
        ...nodeBuiltins
    ],
    format: "cjs",
    target: "es2020",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
    minify: prod,
    // Define globals to help with module resolution
    define: {
        'process.env.NODE_ENV': prod ? '"production"' : '"development"',
    },
    // Platform node is better for Electron environment
    platform: "node",
    // Plugins
    plugins: [inlineWasmPlugin],
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
